name: goku
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.3.1
  - pytorch=1.10.1
  - torchvision=0.11.2
  - cudatoolkit=11.3
  - pyg=2.0.4
  - numpy=1.21.2
  - scipy=1.7.3
  - networkx=2.6.3
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - pandas=1.3.5
  - tqdm=4.62.3
  - numba=0.55.1
  - pip:
    - attrdict==2.0.1
    - ogb==1.3.3
    - wandb==0.12.11 