search_space:
  k_guess:
    _type: choice
    _value: [ 10,5, 15, 20]
  step_size:
    _type: choice
    _value: [0.01]
  beta:
    _type: choice
    _value: [1.0]
  dropout:
    _type: choice
    _value: [0.0]
  dataset:
    _type: choice
    _value: ["mutag" ]
  patience:
    _type: choice
    _value: [100]


trial_command: python run_graph_classification.py
trial_code_directory: .

trial_concurrency: 4
max_trial_number: 500

tuner:
  name: GridSearch
#  class_args:
#    optimize_mode: maximize

training_service:
  platform: local
